version = 0.1

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
s3_prefix = "Slackrock"
stack_name = "Slackrock"

[default.sync.parameters]
watch = true
